name: job-matrix

on:
  push:
    paths:
      - '07-job-matrix/**'
      - '.github/workflows/07-job-matrix.yml'
  
jobs:
  my-job:
    strategy:
      matrix:
        os: ['ubuntu:18.04', 'ubuntu:20.04']
        node: [12, 14, 16]
        exclude:
        - os: ubuntu-18.04
          node: 12

    runs-on: [ self-hosted, Linux, docker ]   
    container: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
       
      - name: Print OS-release
        run: cat /etc/os-release
        
      - name: Run tests
        working-directory: ./07-job-matrix
        run: npm test
       
      - name: Install tmate
        if: ${{ failure() }}
        run: apt update && apt install tmate -y && apt install sudo -y
        
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.11